config/routes.rb
Rails.application.routes.draw do
  root :to => 'homes#index'

  resources :recipes do
    get :search, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  include PgSearch::Model

  validates :name, presence: true
  validates :ingredients, presence: true

  pg_search_scope :search_by_ingredients,
    against: :ingredients,
    ignoring: :accents,
    using: {
      tsearch: {
        dictionary: 'french',
        tsvector_column: "tsv",
        prefix: true
      }
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index; end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_recipe, only: %i[ show edit update destroy ]

  def index
    @recipes = search_recipes.page(page)

    respond_to do |format|
      format.html { render :index, status: :ok }
      format.json { render json: { recipes: @recipes }, status: :ok }
    end
  end

  def search
    @recipes = Recipe.search_by_ingredients(params[:ingredients]).page(page)

    render json: { recipes: @recipes }, status: :ok
  end

  def show
    @recipes = Recipe.all

    respond_to do |format|
      if @recipe
        format.html { render :show, status: :ok }
        format.json { render json: @recipe, status: :ok }
      else
        format.html { redirect_to recipes_url, notice: "Recipe with id #{params[:id]} not found" }
        format.json { render_not_found }
      end
    end
  end

  def new
    @recipe = Recipe.new
  end

  def edit
  end

  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: "Recipe was successfully created." }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: "Recipe was successfully updated." }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: "Recipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def search_recipes
    params[:ingredients] ? Recipe.search_by_ingredients(params[:ingredients]) : Recipe.all
  end

  def set_recipe
    @recipe = Recipe.find_by_id(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :ingredients, :rate, :author_tip, :budget, :prep_time, :author, :difficulty, :people_quantity, :cook_time, :tags, :total_time, :image, :nb_comments)
  end

  def render_not_found(error = nil)
    error ||= "Recipe with id #{params[:id]} not found"
    render json: { error: error }, status: :not_found
  end

  def page
    params[:page] || 1
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homes/index.html.haml
= javascript_pack_tag 'home'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Cookizzy
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/recipes/_form.html.haml
= form_with(model: recipe) do |form|
  - if recipe.errors.any?
    #error_explanation
      %h2
        = pluralize(recipe.errors.count, "error")
        prohibited this recipe from being saved:
      %ul
        - recipe.errors.each do |error|
          %li= error.full_message
  .field
    = form.label :name
    = form.text_field :name
  .field
    = form.label :ingredients
    = form.text_area :ingredients
  .actions
    = form.submit

app/views/recipes/_search_form.html.haml
= form_tag(recipes_path, method: :get) do
  .field
    = text_field_tag(:ingredients, params[:ingredients])
  .actions
    = submit_tag 'chercher'

app/views/recipes/edit.html.haml
%h1 Editing Recipe
= render 'form', recipe: @recipe
= link_to 'Show', @recipe
|
= link_to 'Back', recipes_path

app/views/recipes/index.html.haml
%p#notice= notice
%h1 Search
= render 'search_form'
%h1 Recipes
%table
  %thead
    %tr
      %th Name
      %th{:colspan => "3"}
  %tbody
    - @recipes.each do |recipe|
      %tr
        %td= recipe.name
        %td= link_to 'Show', recipe
        %td= link_to 'Edit', edit_recipe_path(recipe)
        %td= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Recipe', new_recipe_path
%p
  = paginate @recipes

app/views/recipes/new.html.haml
%h1 New Recipe
= render 'form', recipe: @recipe
= link_to 'Back', recipes_path

app/views/recipes/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @recipe.name
%p
  %strong Preparation time:
  = @recipe.prep_time
%p
  %strong Difficulty:
  = @recipe.difficulty
%p
  %strong Ingredients:
%ul
  - @recipe.ingredients.split(',').each do |ingredient|
    %li= ingredient
= link_to 'Edit', edit_recipe_path(@recipe)
|
= link_to 'Back', recipes_path